/* This file was autogenerated by 'imageParser.py' on 17 April 2014 at 19:40 from the directory 'fonts'.
 */
/* _____
 * _____
 * _WW__
 * ___W_
 * _WWW_
 * W__W_
 * _WW_W
 * _____
 */
const uint8_t lowA[] = {0x20, 0x54, 0x54, 0x38, 0x40};

/* WW___
 * _W___
 * _WWW_
 * _W__W
 * _W__W
 * _W__W
 * _WWW_
 * _____
 */
const uint8_t lowB[] = {0x1, 0x7f, 0x44, 0x44, 0x38};

/* ___
 * ___
 * _WW
 * W__
 * W__
 * W__
 * _WW
 * ___
 */
const uint8_t lowC[] = {0x38, 0x44, 0x44};

/* ___WW
 * ___W_
 * _WWW_
 * W__W_
 * W__W_
 * W__W_
 * _WW_W
 * _____
 */
const uint8_t lowD[] = {0x38, 0x44, 0x44, 0x3f, 0x41};

/* ____
 * ____
 * _WW_
 * W__W
 * WWWW
 * W___
 * _WWW
 * ____
 */
const uint8_t lowE[] = {0x38, 0x54, 0x54, 0x58};

/* _WW_
 * W__W
 * W___
 * WWW_
 * W___
 * W___
 * W___
 * ____
 */
const uint8_t lowF[] = {0x7e, 0x9, 0x9, 0x2};

/* ____
 * ____
 * _WW_
 * W__W
 * W__W
 * _WWW
 * ___W
 * WWW_
 */
const uint8_t lowG[] = {0x98, 0xa4, 0xa4, 0x78};

/* W___
 * W___
 * WWW_
 * W__W
 * W__W
 * W__W
 * W__W
 * ____
 */
const uint8_t lowH[] = {0x7f, 0x4, 0x4, 0x78};

/* _W__
 * ____
 * WW__
 * _W__
 * _W__
 * _W_W
 * __W_
 * ____
 */
const uint8_t lowI[] = {0x4, 0x3d, 0x40, 0x20};

/* __W
 * ___
 * __W
 * __W
 * __W
 * __W
 * __W
 * WW_
 */
const uint8_t lowJ[] = {0x80, 0x80, 0x7d};

/* WW___
 * _W___
 * _W_WW
 * _WW_W
 * _WWW_
 * _W_W_
 * _W__W
 * _____
 */
const uint8_t lowK[] = {0x1, 0x7f, 0x18, 0x34, 0x4c};

/* WW__
 * _W__
 * _W__
 * _W__
 * _W__
 * _W_W
 * __W_
 * ____
 */
const uint8_t lowL[] = {0x1, 0x3f, 0x40, 0x20};

/* ______
 * ______
 * W_W_W_
 * WW_W_W
 * W__W_W
 * W____W
 * W____W
 * ______
 */
const uint8_t lowM[] = {0x7c, 0x8, 0x4, 0x18, 0x4, 0x78};

/* ____
 * ____
 * W_W_
 * WW_W
 * W__W
 * W__W
 * W__W
 * ____
 */
const uint8_t lowN[] = {0x7c, 0x8, 0x4, 0x78};

/* ____
 * ____
 * _WW_
 * W__W
 * W__W
 * W__W
 * _WW_
 * ____
 */
const uint8_t lowO[] = {0x38, 0x44, 0x44, 0x38};

/* ____
 * ____
 * WWW_
 * W__W
 * W__W
 * WWW_
 * W___
 * W___
 */
const uint8_t lowP[] = {0xfc, 0x24, 0x24, 0x18};

/* _____
 * _____
 * _WW__
 * W__W_
 * W__W_
 * _WWW_
 * ___W_
 * ___WW
 */
const uint8_t lowQ[] = {0x18, 0x24, 0x24, 0xf8, 0x80};

/* ____
 * ____
 * W_WW
 * WW__
 * W___
 * W___
 * W___
 * ____
 */
const uint8_t lowR[] = {0x7c, 0x8, 0x4, 0x4};

/* ____
 * ____
 * _WW_
 * W___
 * _WW_
 * ___W
 * _WW_
 * ____
 */
const uint8_t lowS[] = {0x8, 0x54, 0x54, 0x20};

/* ____
 * _W__
 * WWW_
 * _W__
 * _W__
 * _W_W
 * __W_
 * ____
 */
const uint8_t lowT[] = {0x4, 0x3e, 0x44, 0x20};

/* _____
 * _____
 * W__W_
 * W__W_
 * W__W_
 * W__W_
 * _WW_W
 * _____
 */
const uint8_t lowU[] = {0x3c, 0x40, 0x40, 0x3c, 0x40};

/* _____
 * _____
 * W___W
 * W___W
 * W___W
 * _W_W_
 * __W__
 * _____
 */
const uint8_t lowV[] = {0x1c, 0x20, 0x40, 0x20, 0x1c};

/* _____
 * _____
 * W___W
 * W___W
 * W_W_W
 * W_W_W
 * _W_W_
 * _____
 */
const uint8_t lowW[] = {0x3c, 0x40, 0x30, 0x40, 0x3c};

/* _____
 * _____
 * W___W
 * _W_W_
 * __W__
 * _W_W_
 * W___W
 * _____
 */
const uint8_t lowX[] = {0x44, 0x28, 0x10, 0x28, 0x44};

/* ____
 * ____
 * W__W
 * W__W
 * W__W
 * _WWW
 * ___W
 * WWW_
 */
const uint8_t lowY[] = {0x9c, 0xa0, 0xa0, 0x7c};

/* ___
 * ___
 * WWW
 * __W
 * _W_
 * W__
 * WWW
 * ___
 */
const uint8_t lowZ[] = {0x64, 0x54, 0x4c};

const uint8_t* lowerCase[] = {lowA, lowB, lowC, lowD, lowE, lowF, lowG, lowH, lowI, lowJ, lowK, lowL, lowM, lowN, lowO, lowP, lowQ, lowR, lowS, lowT, lowU, lowV, lowW, lowX, lowY, lowZ};
const uint8_t lowerCaseWidths[] = {5, 5, 3, 5, 4, 4, 4, 4, 4, 3, 5, 4, 6, 4, 4, 4, 5, 4, 4, 4, 5, 5, 5, 5, 4, 3};
/* _WW_
 * W__W
 * W__W
 * W__W
 * W__W
 * W__W
 * _WW_
 * ____
 */
const uint8_t num0[] = {0x3e, 0x41, 0x41, 0x3e};

/* _W_
 * WW_
 * _W_
 * _W_
 * _W_
 * _W_
 * WWW
 * ___
 */
const uint8_t num1[] = {0x42, 0x7f, 0x40};

/* _WW_
 * W__W
 * ___W
 * __W_
 * _W__
 * W___
 * WWWW
 * ____
 */
const uint8_t num2[] = {0x62, 0x51, 0x49, 0x46};

/* WWWW
 * ___W
 * __W_
 * _WW_
 * ___W
 * ___W
 * WWW_
 * ____
 */
const uint8_t num3[] = {0x41, 0x49, 0x4d, 0x33};

/* ___W_
 * __WW_
 * _W_W_
 * WWWWW
 * ___W_
 * ___W_
 * ___W_
 * _____
 */
const uint8_t num4[] = {0x8, 0xc, 0xa, 0x7f, 0x8};

/* WWWW
 * W___
 * W___
 * WWW_
 * ___W
 * ___W
 * WWW_
 * ____
 */
const uint8_t num5[] = {0x4f, 0x49, 0x49, 0x31};

/* __WW
 * _W__
 * W___
 * WWW_
 * W__W
 * W__W
 * _WW_
 * ____
 */
const uint8_t num6[] = {0x3c, 0x4a, 0x49, 0x31};

/* WWWW
 * ___W
 * __W_
 * __W_
 * _W__
 * _W__
 * _W__
 * ____
 */
const uint8_t num7[] = {0x1, 0x71, 0xd, 0x3};

/* _WW_
 * W__W
 * W__W
 * _WW_
 * W__W
 * W__W
 * _WW_
 * ____
 */
const uint8_t num8[] = {0x36, 0x49, 0x49, 0x36};

/* _WW_
 * W__W
 * W__W
 * _WWW
 * ___W
 * __W_
 * WW__
 * ____
 */
const uint8_t num9[] = {0x46, 0x49, 0x29, 0x1e};

const uint8_t* numbers[] = {num0, num1, num2, num3, num4, num5, num6, num7, num8, num9};
const uint8_t numbersWidths[] = {4, 3, 4, 4, 5, 4, 4, 4, 4, 4};
/* __W__
 * _W_W_
 * WW__W
 * WWWWW
 * WW__W
 * WW__W
 * WW__W
 * _____
 */
const uint8_t upA[] = {0x7c, 0x7e, 0x9, 0xa, 0x7c};

/* WWWW_
 * WW__W
 * WW__W
 * WWWW_
 * WW__W
 * WW__W
 * WWWW_
 * _____
 */
const uint8_t upB[] = {0x7f, 0x7f, 0x49, 0x49, 0x36};

/* _WWW_
 * WW__W
 * WW___
 * WW___
 * WW___
 * WW__W
 * _WWW_
 * _____
 */
const uint8_t upC[] = {0x3e, 0x7f, 0x41, 0x41, 0x22};

/* WWWW_
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * WWWW_
 * _____
 */
const uint8_t upD[] = {0x7f, 0x7f, 0x41, 0x41, 0x3e};

/* WWWWW
 * WW___
 * WW___
 * WWWW_
 * WW___
 * WW___
 * WWWWW
 * _____
 */
const uint8_t upE[] = {0x7f, 0x7f, 0x49, 0x49, 0x41};

/* WWWWW
 * WW___
 * WW___
 * WWWW_
 * WW___
 * WW___
 * WW___
 * _____
 */
const uint8_t upF[] = {0x7f, 0x7f, 0x9, 0x9, 0x1};

/* _WWW_
 * WW___
 * WW___
 * WW_WW
 * WW__W
 * WW__W
 * _WWW_
 * _____
 */
const uint8_t upG[] = {0x3e, 0x7f, 0x41, 0x49, 0x38};

/* WW__W
 * WW__W
 * WW__W
 * WWWWW
 * WW__W
 * WW__W
 * WW__W
 * _____
 */
const uint8_t upH[] = {0x7f, 0x7f, 0x8, 0x8, 0x7f};

/* WWWW
 * _WW_
 * _WW_
 * _WW_
 * _WW_
 * _WW_
 * WWWW
 * ____
 */
const uint8_t upI[] = {0x41, 0x7f, 0x7f, 0x41};

/* _WWWW
 * ___WW
 * ___WW
 * ___WW
 * ___WW
 * W__WW
 * _WWW_
 * _____
 */
const uint8_t upJ[] = {0x20, 0x41, 0x41, 0x7f, 0x3f};

/* WW__W
 * WW__W
 * WW_W_
 * WWW__
 * WW_W_
 * WW__W
 * WW__W
 * _____
 */
const uint8_t upK[] = {0x7f, 0x7f, 0x8, 0x14, 0x63};

/* WW___
 * WW___
 * WW___
 * WW___
 * WW___
 * WW___
 * WWWWW
 * _____
 */
const uint8_t upL[] = {0x7f, 0x7f, 0x40, 0x40, 0x40};

/* WW___W
 * WWW_WW
 * WW_W_W
 * WW_W_W
 * WW___W
 * WW___W
 * WW___W
 * ______
 */
const uint8_t upM[] = {0x7f, 0x7f, 0x2, 0xc, 0x2, 0x7f};

/* WW__W
 * WWW_W
 * WWW_W
 * WW_WW
 * WW_WW
 * WW__W
 * WW__W
 * _____
 */
const uint8_t upN[] = {0x7f, 0x7f, 0x6, 0x18, 0x7f};

/* _WWW_
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * _WWW_
 * _____
 */
const uint8_t upO[] = {0x3e, 0x7f, 0x41, 0x41, 0x3e};

/* WWWW_
 * WW__W
 * WW__W
 * WWWW_
 * WW___
 * WW___
 * WW___
 * _____
 */
const uint8_t upP[] = {0x7f, 0x7f, 0x9, 0x9, 0x6};

/* _WWW__
 * WW__W_
 * WW__W_
 * WW__W_
 * WWW_W_
 * WW_WW_
 * _WWWW_
 * _____W
 */
const uint8_t upQ[] = {0x3e, 0x7f, 0x51, 0x61, 0x7e, 0x80};

/* WWWW_
 * WW__W
 * WW__W
 * WWWW_
 * WW__W
 * WW__W
 * WW__W
 * _____
 */
const uint8_t upR[] = {0x7f, 0x7f, 0x9, 0x9, 0x76};

/* _WWW_
 * WW__W
 * WW___
 * _WWW_
 * ___WW
 * W__WW
 * _WWW_
 * _____
 */
const uint8_t upS[] = {0x26, 0x4f, 0x49, 0x79, 0x32};

/* WWWWWW
 * __WW__
 * __WW__
 * __WW__
 * __WW__
 * __WW__
 * __WW__
 * ______
 */
const uint8_t upT[] = {0x1, 0x1, 0x7f, 0x7f, 0x1, 0x1};

/* WW__W
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * _WWW_
 * _____
 */
const uint8_t upU[] = {0x3f, 0x7f, 0x40, 0x40, 0x3f};

/* WW__W
 * WW__W
 * WW__W
 * WW__W
 * WW__W
 * _W_W_
 * __W__
 * _____
 */
const uint8_t upV[] = {0x1f, 0x3f, 0x40, 0x20, 0x1f};

/* WW_____W
 * WW_____W
 * WW_____W
 * WW__W__W
 * WW__W__W
 * _W_W_W_W
 * __W___W_
 * ________
 */
const uint8_t upW[] = {0x1f, 0x3f, 0x40, 0x20, 0x18, 0x20, 0x40, 0x3f};

/* W___W
 * WW_WW
 * _WWW_
 * __W__
 * _WWW_
 * WW_WW
 * W___W
 * _____
 */
const uint8_t upX[] = {0x63, 0x36, 0x1c, 0x36, 0x63};

/* W___W
 * WW_W_
 * WW_W_
 * _WW__
 * _WW__
 * _WW__
 * _WW__
 * _____
 */
const uint8_t upY[] = {0x7, 0x7e, 0x78, 0x6, 0x1};

/* WWWWW
 * ___WW
 * __WWW
 * _WWW_
 * WWW__
 * WW___
 * WWWWW
 * _____
 */
const uint8_t upZ[] = {0x71, 0x79, 0x5d, 0x4f, 0x47};

const uint8_t* upperCase[] = {upA, upB, upC, upD, upE, upF, upG, upH, upI, upJ, upK, upL, upM, upN, upO, upP, upQ, upR, upS, upT, upU, upV, upW, upX, upY, upZ};
const uint8_t upperCaseWidths[] = {5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 8, 5, 5, 5};
