/* This file was autogenerated by 'levelParser.py' on 14 April 2014 at 20:54 from the directory 'levels'.
 */
/* Level 1
 * Score: 15000
 * ************
 * ************
 * ************
 * ************
 *  ****  **** 
 *   **    **  
 *             
 *             
 */
const char level01_row0[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level01_row1[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level01_row2[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level01_row3[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level01_row4[] = LEVEL_ROW(0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0);
const char level01_row5[] = LEVEL_ROW(0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0);
const char level01_row6[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char level01_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level01[] = {level01_row0, level01_row1, level01_row2, level01_row3, level01_row4, level01_row5, level01_row6, level01_row7};

/* Level 2
 * Score: 22000
 * %%%%%%%%%%%%
 * ************
 * %%%#%%%%#%%%
 * ************
 * %%%%%%%%%%%%
 * ************
 *             
 *             
 */
const char level02_row0[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level02_row1[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level02_row2[] = LEVEL_ROW(3, 3, 3, 5, 3, 3, 3, 3, 5, 3, 3, 3);
const char level02_row3[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level02_row4[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level02_row5[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level02_row6[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char level02_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level02[] = {level02_row0, level02_row1, level02_row2, level02_row3, level02_row4, level02_row5, level02_row6, level02_row7};

/* Level 3
 * Score: 20400
 * *****%%*****
 * ****%**%****
 * ***%****%***
 * **%******%**
 * *%***##***%*
 * %***#**#***%
 *             
 *             
 */
const char level03_row0[] = LEVEL_ROW(2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2);
const char level03_row1[] = LEVEL_ROW(2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2);
const char level03_row2[] = LEVEL_ROW(2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2);
const char level03_row3[] = LEVEL_ROW(2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2);
const char level03_row4[] = LEVEL_ROW(2, 3, 2, 2, 2, 5, 5, 2, 2, 2, 3, 2);
const char level03_row5[] = LEVEL_ROW(3, 2, 2, 2, 5, 2, 2, 5, 2, 2, 2, 3);
const char level03_row6[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char level03_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level03[] = {level03_row0, level03_row1, level03_row2, level03_row3, level03_row4, level03_row5, level03_row6, level03_row7};

/* Level 4
 * Score: 26200
 * %%%%%%%%%%%%
 * %**********%
 * %*%%%%%%%%*%
 * %*%******%*%
 * %*%%%%%%%%*%
 * %**********%
 * %%%%%%%%%%%%
 *             
 */
const char level04_row0[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level04_row1[] = LEVEL_ROW(3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3);
const char level04_row2[] = LEVEL_ROW(3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3);
const char level04_row3[] = LEVEL_ROW(3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3);
const char level04_row4[] = LEVEL_ROW(3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3);
const char level04_row5[] = LEVEL_ROW(3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3);
const char level04_row6[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level04_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level04[] = {level04_row0, level04_row1, level04_row2, level04_row3, level04_row4, level04_row5, level04_row6, level04_row7};

/* Level 5
 * Score: 30800
 * ***#****#***
 * ***#****#***
 * ***#****#***
 * %%%#%%%%#%%%
 * ***#****#***
 * ***#****#***
 * ***#****#***
 * %%%#%%%%#%%%
 */
const char level05_row0[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level05_row1[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level05_row2[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level05_row3[] = LEVEL_ROW(3, 3, 3, 5, 3, 3, 3, 3, 5, 3, 3, 3);
const char level05_row4[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level05_row5[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level05_row6[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level05_row7[] = LEVEL_ROW(3, 3, 3, 5, 3, 3, 3, 3, 5, 3, 3, 3);
const char* level05[] = {level05_row0, level05_row1, level05_row2, level05_row3, level05_row4, level05_row5, level05_row6, level05_row7};

/* Level 6
 * Score: 27400
 * ************
 * ************
 * **###**###**
 * ***#****#***
 * ************
 * *%********%*
 * **%******%**
 * ***%%%%%%***
 */
const char level06_row0[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level06_row1[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level06_row2[] = LEVEL_ROW(2, 2, 5, 5, 5, 2, 2, 5, 5, 5, 2, 2);
const char level06_row3[] = LEVEL_ROW(2, 2, 2, 5, 2, 2, 2, 2, 5, 2, 2, 2);
const char level06_row4[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level06_row5[] = LEVEL_ROW(2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2);
const char level06_row6[] = LEVEL_ROW(2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2);
const char level06_row7[] = LEVEL_ROW(2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2);
const char* level06[] = {level06_row0, level06_row1, level06_row2, level06_row3, level06_row4, level06_row5, level06_row6, level06_row7};

/* Level 7
 * Score: 25200
 * XXXXXXXXXXXX
 * %%%%%%%%%%%%
 * ************
 * XXXXXXXXXXXX
 * %%%%%%%%%%%%
 * ************
 *             
 *             
 */
const char level07_row0[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4);
const char level07_row1[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level07_row2[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level07_row3[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4);
const char level07_row4[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level07_row5[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level07_row6[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char level07_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level07[] = {level07_row0, level07_row1, level07_row2, level07_row3, level07_row4, level07_row5, level07_row6, level07_row7};

/* Level 8
 * Score: 21600
 * ************
 * ************
 * ************
 * **X***X***X*
 * *X%X*X%X*X%X
 * X% %X% %X% %
 * %   %   %   
 *             
 */
const char level08_row0[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level08_row1[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level08_row2[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2);
const char level08_row3[] = LEVEL_ROW(2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2);
const char level08_row4[] = LEVEL_ROW(2, 4, 3, 4, 2, 4, 3, 4, 2, 4, 3, 4);
const char level08_row5[] = LEVEL_ROW(4, 3, 0, 3, 4, 3, 0, 3, 4, 3, 0, 3);
const char level08_row6[] = LEVEL_ROW(3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0);
const char level08_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level08[] = {level08_row0, level08_row1, level08_row2, level08_row3, level08_row4, level08_row5, level08_row6, level08_row7};

/* Level 9
 * Score: 26450
 * ***********X
 * *********XX%
 * ******XXX%%%
 * ***XXX%%%%%X
 * XXX%%%%%%XX 
 * %%%%%%XXX   
 * %%%XXX      
 * XXX         
 */
const char level09_row0[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4);
const char level09_row1[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 3);
const char level09_row2[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 4, 4, 4, 3, 3, 3);
const char level09_row3[] = LEVEL_ROW(2, 2, 2, 4, 4, 4, 3, 3, 3, 3, 3, 4);
const char level09_row4[] = LEVEL_ROW(4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 0);
const char level09_row5[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 4, 4, 4, 0, 0, 0);
const char level09_row6[] = LEVEL_ROW(3, 3, 3, 4, 4, 4, 0, 0, 0, 0, 0, 0);
const char level09_row7[] = LEVEL_ROW(4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level09[] = {level09_row0, level09_row1, level09_row2, level09_row3, level09_row4, level09_row5, level09_row6, level09_row7};

/* Level 10
 * Score: 28800
 * XXXXXX%%%%%%
 * X****X%****%
 * X****X%****%
 * X****X%****%
 * X****X%****%
 * XXXXXX%%%%%%
 * %%%%%%XXXXXX
 *             
 */
const char level10_row0[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3);
const char level10_row1[] = LEVEL_ROW(4, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 3);
const char level10_row2[] = LEVEL_ROW(4, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 3);
const char level10_row3[] = LEVEL_ROW(4, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 3);
const char level10_row4[] = LEVEL_ROW(4, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 3);
const char level10_row5[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3);
const char level10_row6[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4);
const char level10_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level10[] = {level10_row0, level10_row1, level10_row2, level10_row3, level10_row4, level10_row5, level10_row6, level10_row7};

/* Level 11
 * Score: 24000
 * XXXXXXXXXXXX
 * ***%*****%**
 * **%*%***%*%*
 * *%***%*%***%
 * %*****%*****
 * XXXXXXXXXXXX
 *             
 *             
 */
const char level11_row0[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4);
const char level11_row1[] = LEVEL_ROW(2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2);
const char level11_row2[] = LEVEL_ROW(2, 2, 3, 2, 3, 2, 2, 2, 3, 2, 3, 2);
const char level11_row3[] = LEVEL_ROW(2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 2, 3);
const char level11_row4[] = LEVEL_ROW(3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2);
const char level11_row5[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4);
const char level11_row6[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char level11_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level11[] = {level11_row0, level11_row1, level11_row2, level11_row3, level11_row4, level11_row5, level11_row6, level11_row7};

/* Level 12
 * Score: 33200
 * **XXX**XXX**
 * *X%%%XX%%%X*
 * X%%%%%%%%%%X
 * X%%%%%%%%%%X
 * *X%%%%%%%%X*
 * **X%%%%%%X**
 * ***X%%%%X***
 * ****XXXX****
 */
const char level12_row0[] = LEVEL_ROW(2, 2, 4, 4, 4, 2, 2, 4, 4, 4, 2, 2);
const char level12_row1[] = LEVEL_ROW(2, 4, 3, 3, 3, 4, 4, 3, 3, 3, 4, 2);
const char level12_row2[] = LEVEL_ROW(4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4);
const char level12_row3[] = LEVEL_ROW(4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4);
const char level12_row4[] = LEVEL_ROW(2, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2);
const char level12_row5[] = LEVEL_ROW(2, 2, 4, 3, 3, 3, 3, 3, 3, 4, 2, 2);
const char level12_row6[] = LEVEL_ROW(2, 2, 2, 4, 3, 3, 3, 3, 4, 2, 2, 2);
const char level12_row7[] = LEVEL_ROW(2, 2, 2, 2, 4, 4, 4, 4, 2, 2, 2, 2);
const char* level12[] = {level12_row0, level12_row1, level12_row2, level12_row3, level12_row4, level12_row5, level12_row6, level12_row7};

/* Level 13
 * Score: 29000
 * *****X******
 * ****X%X*****
 * ****X%X*****
 * **XX*X*XX***
 * *X%%XXX%%X**
 * **XX*X*XX***
 * *****X******
 * ******X*****
 */
const char level13_row0[] = LEVEL_ROW(2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2);
const char level13_row1[] = LEVEL_ROW(2, 2, 2, 2, 4, 3, 4, 2, 2, 2, 2, 2);
const char level13_row2[] = LEVEL_ROW(2, 2, 2, 2, 4, 3, 4, 2, 2, 2, 2, 2);
const char level13_row3[] = LEVEL_ROW(2, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2);
const char level13_row4[] = LEVEL_ROW(2, 4, 3, 3, 4, 4, 4, 3, 3, 4, 2, 2);
const char level13_row5[] = LEVEL_ROW(2, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2);
const char level13_row6[] = LEVEL_ROW(2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2);
const char level13_row7[] = LEVEL_ROW(2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2);
const char* level13[] = {level13_row0, level13_row1, level13_row2, level13_row3, level13_row4, level13_row5, level13_row6, level13_row7};

/* Level 14
 * Score: 24400
 * **X**XX**X**
 * **X**XX**X**
 * **X**XX**X**
 * **X**XX**X**
 * **X##XX##X**
 * %%%%%%%%%%%%
 *             
 *             
 */
const char level14_row0[] = LEVEL_ROW(2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2);
const char level14_row1[] = LEVEL_ROW(2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2);
const char level14_row2[] = LEVEL_ROW(2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2);
const char level14_row3[] = LEVEL_ROW(2, 2, 4, 2, 2, 4, 4, 2, 2, 4, 2, 2);
const char level14_row4[] = LEVEL_ROW(2, 2, 4, 5, 5, 4, 4, 5, 5, 4, 2, 2);
const char level14_row5[] = LEVEL_ROW(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
const char level14_row6[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char level14_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level14[] = {level14_row0, level14_row1, level14_row2, level14_row3, level14_row4, level14_row5, level14_row6, level14_row7};

/* Level 15
 * Score: 32200
 * XXXXXXXXXXXX
 * X%%%%%%%%%%X
 * X%********%X
 * X%*######*%X
 * X%********%X
 * X%%%%%%%%%%X
 * XXXXXXXXXXXX
 *             
 */
const char level15_row0[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4);
const char level15_row1[] = LEVEL_ROW(4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4);
const char level15_row2[] = LEVEL_ROW(4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4);
const char level15_row3[] = LEVEL_ROW(4, 3, 2, 5, 5, 5, 5, 5, 5, 2, 3, 4);
const char level15_row4[] = LEVEL_ROW(4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4);
const char level15_row5[] = LEVEL_ROW(4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4);
const char level15_row6[] = LEVEL_ROW(4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4);
const char level15_row7[] = LEVEL_ROW(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
const char* level15[] = {level15_row0, level15_row1, level15_row2, level15_row3, level15_row4, level15_row5, level15_row6, level15_row7};

const char** LEVEL_PATTERNS[] = {level01, level02, level03, level04, level05, level06, level07, level08, level09, level10, level11, level12, level13, level14, level15};
#define LAST_LEVEL 15