/* This file was autogenerated by 'spriteParser.py' on 17 April 2014 at 19:43 from the directory 'sprites'.
 */
/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom0[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom1[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom2[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom3[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _WWW_
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom4[] = {0x0, 0x1, 0x1, 0x1, 0x0};

/* W___W
 * _WWW_
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom5[] = {0x1, 0x2, 0x2, 0x2, 0x1};

/* W___W
 * W___W
 * _WWW_
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom6[] = {0x3, 0x4, 0x4, 0x4, 0x3};

/* W___W
 * W___W
 * W___W
 * _WWW_
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t ballBottom7[] = {0x7, 0x8, 0x8, 0x8, 0x7};

const uint8_t* ballBottoms[] = {ballBottom0, ballBottom1, ballBottom2, ballBottom3, ballBottom4, ballBottom5, ballBottom6, ballBottom7};
#define BALL_WIDTH 5
/* _WWW_
 * W___W
 * W___W
 * W___W
 * _WWW_
 * _____
 * _____
 * _____
 */
const uint8_t ball0[] = {0xe, 0x11, 0x11, 0x11, 0xe};

/* _____
 * _WWW_
 * W___W
 * W___W
 * W___W
 * _WWW_
 * _____
 * _____
 */
const uint8_t ball1[] = {0x1c, 0x22, 0x22, 0x22, 0x1c};

/* _____
 * _____
 * _WWW_
 * W___W
 * W___W
 * W___W
 * _WWW_
 * _____
 */
const uint8_t ball2[] = {0x38, 0x44, 0x44, 0x44, 0x38};

/* _____
 * _____
 * _____
 * _WWW_
 * W___W
 * W___W
 * W___W
 * _WWW_
 */
const uint8_t ball3[] = {0x70, 0x88, 0x88, 0x88, 0x70};

/* _____
 * _____
 * _____
 * _____
 * _WWW_
 * W___W
 * W___W
 * W___W
 */
const uint8_t ball4[] = {0xe0, 0x10, 0x10, 0x10, 0xe0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _WWW_
 * W___W
 * W___W
 */
const uint8_t ball5[] = {0xc0, 0x20, 0x20, 0x20, 0xc0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _WWW_
 * W___W
 */
const uint8_t ball6[] = {0x80, 0x40, 0x40, 0x40, 0x80};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _WWW_
 */
const uint8_t ball7[] = {0x0, 0x80, 0x80, 0x80, 0x0};

const uint8_t* ballSprites[] = {ball0, ball1, ball2, ball3, ball4, ball5, ball6, ball7};
#define BALL_WIDTH 5
/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom0[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom1[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom2[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom3[] = {0x0, 0x0, 0x0, 0x0, 0x0};

/* _W_W_
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom4[] = {0x0, 0x1, 0x0, 0x1, 0x0};

/* _WWW_
 * _W_W_
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom5[] = {0x0, 0x3, 0x1, 0x3, 0x0};

/* WWWWW
 * _WWW_
 * _W_W_
 * _____
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom6[] = {0x1, 0x7, 0x3, 0x7, 0x1};

/* __W__
 * WWWWW
 * _WWW_
 * _W_W_
 * _____
 * _____
 * _____
 * _____
 */
const uint8_t powerUpBottom7[] = {0x2, 0xe, 0x7, 0xe, 0x2};

const uint8_t* powerUpBottoms[] = {powerUpBottom0, powerUpBottom1, powerUpBottom2, powerUpBottom3, powerUpBottom4, powerUpBottom5, powerUpBottom6, powerUpBottom7};
#define POWERUP_WIDTH 5
#define BALL_WIDTH 5
/* __W__
 * __W__
 * WWWWW
 * _WWW_
 * _W_W_
 * _____
 * _____
 * _____
 */
const uint8_t powerUp0[] = {0x4, 0x1c, 0xf, 0x1c, 0x4};

/* _____
 * __W__
 * __W__
 * WWWWW
 * _WWW_
 * _W_W_
 * _____
 * _____
 */
const uint8_t powerUp1[] = {0x8, 0x38, 0x1e, 0x38, 0x8};

/* _____
 * _____
 * __W__
 * __W__
 * WWWWW
 * _WWW_
 * _W_W_
 * _____
 */
const uint8_t powerUp2[] = {0x10, 0x70, 0x3c, 0x70, 0x10};

/* _____
 * _____
 * _____
 * __W__
 * __W__
 * WWWWW
 * _WWW_
 * _W_W_
 */
const uint8_t powerUp3[] = {0x20, 0xe0, 0x78, 0xe0, 0x20};

/* _____
 * _____
 * _____
 * _____
 * __W__
 * __W__
 * WWWWW
 * _WWW_
 */
const uint8_t powerUp4[] = {0x40, 0xc0, 0xf0, 0xc0, 0x40};

/* _____
 * _____
 * _____
 * _____
 * _____
 * __W__
 * __W__
 * WWWWW
 */
const uint8_t powerUp5[] = {0x80, 0x80, 0xe0, 0x80, 0x80};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * __W__
 * __W__
 */
const uint8_t powerUp6[] = {0x0, 0x0, 0xc0, 0x0, 0x0};

/* _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * _____
 * __W__
 */
const uint8_t powerUp7[] = {0x0, 0x0, 0x80, 0x0, 0x0};

const uint8_t* powerUpSprites[] = {powerUp0, powerUp1, powerUp2, powerUp3, powerUp4, powerUp5, powerUp6, powerUp7};
#define POWERUP_WIDTH 5
#define BALL_WIDTH 5
